### ISSUE TITLE
Could you please provide the results of each domain?

### ISSUE THREAD

**Issue by judgingalready** [Byounggyu-Lew/gestur#1]
Thanks for the nice work!

Sorry to bother you. Could you please provide the detailed results of **Table 1** **(Using VIT-B pre-trained by CLIP)** for **each domain** on five datasets? It will help me a lot.

Thank you very much.

**Comment by korts-lew** [comment]
Hello, first of all, I want to say thank you for your interest in our work.

This work was done when I was in my previous company, and all of the authors have left the company now.
Thus, we don't have permission to reach the data. I'm sorry to say that we're unable to give the requested results 😢.

I hope things go well for you.

**Comment by judgingalready** [comment]
Thanks for your quick reply! I understand that and sorry to bother you agian.
